#시계열 데이터

In [67]:
#datetime 오브젝트

In [68]:
from datetime import datetime

In [69]:
#현재 시간 출력 방법1
now1 = datetime.now()
print(now1)

2021-10-04 14:29:14.816394

In [70]:
#현재 시간 출력 방법2
now2 = datetime.today()
print(now2)

2021-10-04 14:29:32.924509

In [71]:
#datetime오브젝트를 생성할 때 시간을 직접 입력가능
t1 = datetime.now()
t2 = datetime(1970,1,1)
t3 = datetime(1970,12,12,13,24,34)

In [72]:
print(t1)
print(t2)
print(t3)

2021-10-04 14:30:51.169444
1970-01-01 00:00:00
1970-12-12 13:24:34

In [73]:
#시간 계산하기
diff1 = t1 -t2

In [75]:
print(diff1)
type(diff1)

18904 days, 14:30:51.169444

datetime.timedelta

In [76]:
diff2 = t2 - t1

In [77]:
print(diff2)
print(type(diff2))

-18905 days, 9:29:08.830556
<class 'datetime.timedelta'>

#테슬라 주식 데이터로 시간 계산하기(P.256~

In [1]:
pip install pandas-datareader

Collecting pandas-datareader
  Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
Requirement already satisfied: pandas>=0.23 in c:\users\arwen\anaconda3\lib\site-packages (from pandas-datareader) (1.1.3)
Requirement already satisfied: requests>=2.19.0 in c:\users\arwen\anaconda3\lib\site-packages (from pandas-datareader) (2.24.0)
Requirement already satisfied: lxml in c:\users\arwen\anaconda3\lib\site-packages (from pandas-datareader) (4.6.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\arwen\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (2020.1)
Requirement already satisfied: numpy>=1.15.4 in c:\users\arwen\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (1.19.2)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\arwen\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (2.8.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arwen\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\arwen\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\arwen\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\arwen\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.0.4)
Requirement already satisfied: six>=1.5 in c:\users\arwen\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas-datareader) (1.15.0)
Installing collected packages: pandas-datareader
Successfully installed pandas-datareader-0.10.0
Note: you may need to restart the kernel to use updated packages.

In [35]:
import pandas as pd
import numpy as np

In [4]:
pd.core.common.is_list_like = pd.api.types.is_list_like

In [5]:
import pandas_datareader as pdr

In [18]:
tesla = pdr.get_data_quandl('TSLA',api_key = 'EycKBPyknq9xCyAdEZek')

In [19]:
tesla

,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume
Date,,,,,,,,,,,,
2018-03-27,304.00,304.2700,277.18,279.18,13696168.0,0.0,1.0,304.00,304.2700,277.18,279.18,13696168.0
2018-03-26,307.34,307.5900,291.36,304.18,8324639.0,0.0,1.0,307.34,307.5900,291.36,304.18,8324639.0
2018-03-23,311.25,311.6100,300.45,301.54,6600538.0,0.0,1.0,311.25,311.6100,300.45,301.54,6600538.0
2018-03-22,313.89,318.8200,308.18,309.10,4914307.0,0.0,1.0,313.89,318.8200,308.18,309.10,4914307.0
2018-03-21,310.25,322.4400,310.19,316.53,5927881.0,0.0,1.0,310.25,322.4400,310.19,316.53,5927881.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2016-10-11,201.85,202.2000,198.31,200.10,2328422.0,0.0,1.0,201.85,202.2000,198.31,200.10,2328422.0
2016-10-10,201.35,204.1400,199.66,200.95,3316297.0,0.0,1.0,201.35,204.1400,199.66,200.95,3316297.0
2016-10-07,201.00,201.3200,195.80,196.61,3493018.0,0.0,1.0,201.00,201.3200,195.80,196.61,3493018.0
2016-10-06,202.46,204.2099,200.21,201.00,4703402.0,0.0,1.0,202.46,204.2099,200.21,201.00,4703402.0
2016-10-05,212.24,213.1500,208.12,208.46,1877534.0,0.0,1.0,212.24,213.1500,208.12,208.46,1877534.0

In [20]:
tesla.to_csv('C:/Users/arwen/Documents/ESAA활동(21-2)/5주차 과제/data/tesla_stock_quandl.csv')

In [21]:
print(tesla.head())

              Open    High     Low   Close      Volume  ExDividend  \
Date
2018-03-27  304.00  304.27  277.18  279.18  13696168.0         0.0
2018-03-26  307.34  307.59  291.36  304.18   8324639.0         0.0
2018-03-23  311.25  311.61  300.45  301.54   6600538.0         0.0
2018-03-22  313.89  318.82  308.18  309.10   4914307.0         0.0
2018-03-21  310.25  322.44  310.19  316.53   5927881.0         0.0

            SplitRatio  AdjOpen  AdjHigh  AdjLow  AdjClose   AdjVolume
Date
2018-03-27         1.0   304.00   304.27  277.18    279.18  13696168.0
2018-03-26         1.0   307.34   307.59  291.36    304.18   8324639.0
2018-03-23         1.0   311.25   311.61  300.45    301.54   6600538.0
2018-03-22         1.0   313.89   318.82  308.18    309.10   4914307.0
2018-03-21         1.0   310.25   322.44  310.19    316.53   5927881.0

In [22]:
print(tesla.info())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 370 entries, 2018-03-27 to 2016-10-05
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Open        370 non-null    float64
 1   High        370 non-null    float64
 2   Low         370 non-null    float64
 3   Close       370 non-null    float64
 4   Volume      370 non-null    float64
 5   ExDividend  370 non-null    float64
 6   SplitRatio  370 non-null    float64
 7   AdjOpen     370 non-null    float64
 8   AdjHigh     370 non-null    float64
 9   AdjLow      370 non-null    float64
 10  AdjClose    370 non-null    float64
 11  AdjVolume   370 non-null    float64
dtypes: float64(12)
memory usage: 37.6 KB
None

In [83]:
tesla = pd.read_csv('C:/Users/arwen/Documents/ESAA활동(21-2)/5주차 과제/data/tesla_stock_quandl.csv',parse_dates=[0])
print(tesla.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        370 non-null    datetime64[ns]
 1   Open        370 non-null    float64
 2   High        370 non-null    float64
 3   Low         370 non-null    float64
 4   Close       370 non-null    float64
 5   Volume      370 non-null    float64
 6   ExDividend  370 non-null    float64
 7   SplitRatio  370 non-null    float64
 8   AdjOpen     370 non-null    float64
 9   AdjHigh     370 non-null    float64
 10  AdjLow      370 non-null    float64
 11  AdjClose    370 non-null    float64
 12  AdjVolume   370 non-null    float64
dtypes: datetime64[ns](1), float64(12)
memory usage: 37.7 KB
None

In [84]:
tesla

,Date,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume
0,2018-03-27,304.00,304.2700,277.18,279.18,13696168.0,0.0,1.0,304.00,304.2700,277.18,279.18,13696168.0
1,2018-03-26,307.34,307.5900,291.36,304.18,8324639.0,0.0,1.0,307.34,307.5900,291.36,304.18,8324639.0
2,2018-03-23,311.25,311.6100,300.45,301.54,6600538.0,0.0,1.0,311.25,311.6100,300.45,301.54,6600538.0
3,2018-03-22,313.89,318.8200,308.18,309.10,4914307.0,0.0,1.0,313.89,318.8200,308.18,309.10,4914307.0
4,2018-03-21,310.25,322.4400,310.19,316.53,5927881.0,0.0,1.0,310.25,322.4400,310.19,316.53,5927881.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,2016-10-11,201.85,202.2000,198.31,200.10,2328422.0,0.0,1.0,201.85,202.2000,198.31,200.10,2328422.0
366,2016-10-10,201.35,204.1400,199.66,200.95,3316297.0,0.0,1.0,201.35,204.1400,199.66,200.95,3316297.0
367,2016-10-07,201.00,201.3200,195.80,196.61,3493018.0,0.0,1.0,201.00,201.3200,195.80,196.61,3493018.0
368,2016-10-06,202.46,204.2099,200.21,201.00,4703402.0,0.0,1.0,202.46,204.2099,200.21,201.00,4703402.0
369,2016-10-05,212.24,213.1500,208.12,208.46,1877534.0,0.0,1.0,212.24,213.1500,208.12,208.46,1877534.0

In [27]:
print(tesla.loc[(tesla.Date.dt.year == 2017) & (tesla.Date.dt.month == 6)])

          Date     Open      High       Low   Close      Volume  ExDividend  \
184 2017-06-30  363.710  366.7674  359.6187  361.61   5759458.0         0.0
185 2017-06-29  370.610  371.0000  354.1000  360.75   8180408.0         0.0
186 2017-06-28  366.680  371.7400  362.5200  371.24   6245040.0         0.0
187 2017-06-27  376.400  376.4000  362.0200  362.37   6884529.0         0.0
188 2017-06-26  386.690  386.9500  373.1000  377.49   6575285.0         0.0
189 2017-06-23  382.450  386.9900  379.3450  383.45   6176578.0         0.0
190 2017-06-22  377.990  385.0000  373.5700  382.61   7485677.0         0.0
191 2017-06-21  374.350  376.9900  368.0200  376.40   4900356.0         0.0
192 2017-06-20  376.670  378.8800  369.7300  372.24   7396357.0         0.0
193 2017-06-19  375.000  376.7000  367.8000  369.80   6392331.0         0.0
194 2017-06-16  377.975  378.0100  370.1000  371.40   6259666.0         0.0
195 2017-06-15  372.500  375.4600  366.4900  375.34  10371559.0         0.0
196 2017-06-14  381.085  384.2500  376.3100  380.66  12731997.0         0.0
197 2017-06-13  367.620  376.0000  366.6100  375.95  11693404.0         0.0
198 2017-06-12  357.990  364.5000  350.6200  359.01  10476833.0         0.0
199 2017-06-09  374.420  376.8700  354.8000  357.32  17160231.0         0.0
200 2017-06-08  363.750  371.9000  360.2200  370.00   8975028.0         0.0
201 2017-06-07  356.340  360.5000  355.1400  359.65   9287888.0         0.0
202 2017-06-06  344.700  359.4929  339.9700  352.85  10951473.0         0.0
203 2017-06-05  338.500  348.4400  334.2100  347.32   6737855.0         0.0
204 2017-06-02  339.770  342.8800  335.9300  339.85   5570256.0         0.0
205 2017-06-01  344.000  344.8800  337.2900  340.37   7580447.0         0.0

     SplitRatio  AdjOpen   AdjHigh    AdjLow  AdjClose   AdjVolume
184         1.0  363.710  366.7674  359.6187    361.61   5759458.0
185         1.0  370.610  371.0000  354.1000    360.75   8180408.0
186         1.0  366.680  371.7400  362.5200    371.24   6245040.0
187         1.0  376.400  376.4000  362.0200    362.37   6884529.0
188         1.0  386.690  386.9500  373.1000    377.49   6575285.0
189         1.0  382.450  386.9900  379.3450    383.45   6176578.0
190         1.0  377.990  385.0000  373.5700    382.61   7485677.0
191         1.0  374.350  376.9900  368.0200    376.40   4900356.0
192         1.0  376.670  378.8800  369.7300    372.24   7396357.0
193         1.0  375.000  376.7000  367.8000    369.80   6392331.0
194         1.0  377.975  378.0100  370.1000    371.40   6259666.0
195         1.0  372.500  375.4600  366.4900    375.34  10371559.0
196         1.0  381.085  384.2500  376.3100    380.66  12731997.0
197         1.0  367.620  376.0000  366.6100    375.95  11693404.0
198         1.0  357.990  364.5000  350.6200    359.01  10476833.0
199         1.0  374.420  376.8700  354.8000    357.32  17160231.0
200         1.0  363.750  371.9000  360.2200    370.00   8975028.0
201         1.0  356.340  360.5000  355.1400    359.65   9287888.0
202         1.0  344.700  359.4929  339.9700    352.85  10951473.0
203         1.0  338.500  348.4400  334.2100    347.32   6737855.0
204         1.0  339.770  342.8800  335.9300    339.85   5570256.0
205         1.0  344.000  344.8800  337.2900    340.37   7580447.0

In [85]:
tesla.index = tesla['Date']
print(tesla.index)

DatetimeIndex(['2018-03-27', '2018-03-26', '2018-03-23', '2018-03-22',
               '2018-03-21', '2018-03-20', '2018-03-19', '2018-03-16',
               '2018-03-15', '2018-03-14',
               ...
               '2016-10-18', '2016-10-17', '2016-10-14', '2016-10-13',
               '2016-10-12', '2016-10-11', '2016-10-10', '2016-10-07',
               '2016-10-06', '2016-10-05'],
              dtype='datetime64[ns]', name='Date', length=370, freq=None)

In [86]:
tesla

,Date,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume
Date,,,,,,,,,,,,,
2018-03-27,2018-03-27,304.00,304.2700,277.18,279.18,13696168.0,0.0,1.0,304.00,304.2700,277.18,279.18,13696168.0
2018-03-26,2018-03-26,307.34,307.5900,291.36,304.18,8324639.0,0.0,1.0,307.34,307.5900,291.36,304.18,8324639.0
2018-03-23,2018-03-23,311.25,311.6100,300.45,301.54,6600538.0,0.0,1.0,311.25,311.6100,300.45,301.54,6600538.0
2018-03-22,2018-03-22,313.89,318.8200,308.18,309.10,4914307.0,0.0,1.0,313.89,318.8200,308.18,309.10,4914307.0
2018-03-21,2018-03-21,310.25,322.4400,310.19,316.53,5927881.0,0.0,1.0,310.25,322.4400,310.19,316.53,5927881.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-10-11,2016-10-11,201.85,202.2000,198.31,200.10,2328422.0,0.0,1.0,201.85,202.2000,198.31,200.10,2328422.0
2016-10-10,2016-10-10,201.35,204.1400,199.66,200.95,3316297.0,0.0,1.0,201.35,204.1400,199.66,200.95,3316297.0
2016-10-07,2016-10-07,201.00,201.3200,195.80,196.61,3493018.0,0.0,1.0,201.00,201.3200,195.80,196.61,3493018.0
2016-10-06,2016-10-06,202.46,204.2099,200.21,201.00,4703402.0,0.0,1.0,202.46,204.2099,200.21,201.00,4703402.0
2016-10-05,2016-10-05,212.24,213.1500,208.12,208.46,1877534.0,0.0,1.0,212.24,213.1500,208.12,208.46,1877534.0

In [34]:
type(tesla)

pandas.core.frame.DataFrame

In [38]:
print(tesla['2018-03'].iloc[:,:5])

AssertionError: <class 'numpy.ndarray'>

In [41]:
tesla['ref_date']=tesla['Date']-tesla['Date'].min()
print(tesla.head())

                 Date    Open    High     Low   Close      Volume  ExDividend  \
Date
2018-03-27 2018-03-27  304.00  304.27  277.18  279.18  13696168.0         0.0
2018-03-26 2018-03-26  307.34  307.59  291.36  304.18   8324639.0         0.0
2018-03-23 2018-03-23  311.25  311.61  300.45  301.54   6600538.0         0.0
2018-03-22 2018-03-22  313.89  318.82  308.18  309.10   4914307.0         0.0
2018-03-21 2018-03-21  310.25  322.44  310.19  316.53   5927881.0         0.0

            SplitRatio  AdjOpen  AdjHigh  AdjLow  AdjClose   AdjVolume  \
Date
2018-03-27         1.0   304.00   304.27  277.18    279.18  13696168.0
2018-03-26         1.0   307.34   307.59  291.36    304.18   8324639.0
2018-03-23         1.0   311.25   311.61  300.45    301.54   6600538.0
2018-03-22         1.0   313.89   318.82  308.18    309.10   4914307.0
2018-03-21         1.0   310.25   322.44  310.19    316.53   5927881.0

           ref_date
Date
2018-03-27 538 days
2018-03-26 537 days
2018-03-23 534 days
2018-03-22 533 days
2018-03-21 532 days

In [43]:
tesla.index = tesla['ref_date']

In [44]:
tesla

,Date,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume,ref_date
ref_date,,,,,,,,,,,,,,
538 days,2018-03-27,304.00,304.2700,277.18,279.18,13696168.0,0.0,1.0,304.00,304.2700,277.18,279.18,13696168.0,538 days
537 days,2018-03-26,307.34,307.5900,291.36,304.18,8324639.0,0.0,1.0,307.34,307.5900,291.36,304.18,8324639.0,537 days
534 days,2018-03-23,311.25,311.6100,300.45,301.54,6600538.0,0.0,1.0,311.25,311.6100,300.45,301.54,6600538.0,534 days
533 days,2018-03-22,313.89,318.8200,308.18,309.10,4914307.0,0.0,1.0,313.89,318.8200,308.18,309.10,4914307.0,533 days
532 days,2018-03-21,310.25,322.4400,310.19,316.53,5927881.0,0.0,1.0,310.25,322.4400,310.19,316.53,5927881.0,532 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6 days,2016-10-11,201.85,202.2000,198.31,200.10,2328422.0,0.0,1.0,201.85,202.2000,198.31,200.10,2328422.0,6 days
5 days,2016-10-10,201.35,204.1400,199.66,200.95,3316297.0,0.0,1.0,201.35,204.1400,199.66,200.95,3316297.0,5 days
2 days,2016-10-07,201.00,201.3200,195.80,196.61,3493018.0,0.0,1.0,201.00,201.3200,195.80,196.61,3493018.0,2 days
1 days,2016-10-06,202.46,204.2099,200.21,201.00,4703402.0,0.0,1.0,202.46,204.2099,200.21,201.00,4703402.0,1 days
0 days,2016-10-05,212.24,213.1500,208.12,208.46,1877534.0,0.0,1.0,212.24,213.1500,208.12,208.46,1877534.0,0 days

In [45]:
print(tesla.iloc[:5,:5])

               Date    Open    High     Low   Close
ref_date
538 days 2018-03-27  304.00  304.27  277.18  279.18
537 days 2018-03-26  307.34  307.59  291.36  304.18
534 days 2018-03-23  311.25  311.61  300.45  301.54
533 days 2018-03-22  313.89  318.82  308.18  309.10
532 days 2018-03-21  310.25  322.44  310.19  316.53

In [49]:
print(tesla['5 days':].iloc[:,:5])

               Date    Open      High     Low   Close
ref_date
5 days   2016-10-10  201.35  204.1400  199.66  200.95
2 days   2016-10-07  201.00  201.3200  195.80  196.61
1 days   2016-10-06  202.46  204.2099  200.21  201.00
0 days   2016-10-05  212.24  213.1500  208.12  208.46

In [50]:
print(tesla['5 days':].iloc[:5,:5])

               Date    Open      High     Low   Close
ref_date
5 days   2016-10-10  201.35  204.1400  199.66  200.95
2 days   2016-10-07  201.00  201.3200  195.80  196.61
1 days   2016-10-06  202.46  204.2099  200.21  201.00
0 days   2016-10-05  212.24  213.1500  208.12  208.46

#에볼라 시계열 데이터 분석

In [51]:
import os

In [53]:
#깃허브에서 raw 버튼 클릭
ebola = pd.read_csv('https://raw.githubusercontent.com/easysIT/doit_pandas/master/data/country_timeseries.csv')

In [55]:
#내 컴퓨터 폴터에 country_timeseries.csv파일 csv파일 형태로 저장
ebola.to_csv('C:/Users/arwen/Documents/ESAA활동(21-2)/5주차 과제/data/country_timeseries.csv')

In [54]:
ebola

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,3/27/2014,5,103.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,66.0,6.0,5.0,NaN,NaN,NaN,NaN,NaN
118,3/26/2014,4,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,3/25/2014,3,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,3/24/2014,2,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,3/22/2014,0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
ebola.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 122 non-null    object
 1   Day                  122 non-null    int64
 2   Cases_Guinea         93 non-null     float64
 3   Cases_Liberia        83 non-null     float64
 4   Cases_SierraLeone    87 non-null     float64
 5   Cases_Nigeria        38 non-null     float64
 6   Cases_Senegal        25 non-null     float64
 7   Cases_UnitedStates   18 non-null     float64
 8   Cases_Spain          16 non-null     float64
 9   Cases_Mali           12 non-null     float64
 10  Deaths_Guinea        92 non-null     float64
 11  Deaths_Liberia       81 non-null     float64
 12  Deaths_SierraLeone   87 non-null     float64
 13  Deaths_Nigeria       38 non-null     float64
 14  Deaths_Senegal       22 non-null     float64
 15  Deaths_UnitedStates  18 non-null     float64
 16  Deaths_Spain         16 non-null     float64
 17  Deaths_Mali          12 non-null     float64
dtypes: float64(16), int64(1), object(1)
memory usage: 17.3+ KB

In [57]:
ebola = pd.read_csv('https://raw.githubusercontent.com/easysIT/doit_pandas/master/data/country_timeseries.csv',parse_dates=[0])

In [58]:
ebola.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 122 non-null    datetime64[ns]
 1   Day                  122 non-null    int64
 2   Cases_Guinea         93 non-null     float64
 3   Cases_Liberia        83 non-null     float64
 4   Cases_SierraLeone    87 non-null     float64
 5   Cases_Nigeria        38 non-null     float64
 6   Cases_Senegal        25 non-null     float64
 7   Cases_UnitedStates   18 non-null     float64
 8   Cases_Spain          16 non-null     float64
 9   Cases_Mali           12 non-null     float64
 10  Deaths_Guinea        92 non-null     float64
 11  Deaths_Liberia       81 non-null     float64
 12  Deaths_SierraLeone   87 non-null     float64
 13  Deaths_Nigeria       38 non-null     float64
 14  Deaths_Senegal       22 non-null     float64
 15  Deaths_UnitedStates  18 non-null     float64
 16  Deaths_Spain         16 non-null     float64
 17  Deaths_Mali          12 non-null     float64
dtypes: datetime64[ns](1), float64(16), int64(1)
memory usage: 17.3 KB

시간 범위 생성해 인덱스로 지정하기

In [59]:
#2015-01-01 데이터 누락
print(ebola.iloc[:5,:5])

        Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone
0 2015-01-05  289        2776.0            NaN            10030.0
1 2015-01-04  288        2775.0            NaN             9780.0
2 2015-01-03  287        2769.0         8166.0             9722.0
3 2015-01-02  286           NaN         8157.0                NaN
4 2014-12-31  284        2730.0         8115.0             9633.0

In [60]:
#2014-03-23 데이터 누락
print(ebola.iloc[-5:,:5])

          Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone
117 2014-03-27    5         103.0            8.0                6.0
118 2014-03-26    4          86.0            NaN                NaN
119 2014-03-25    3          86.0            NaN                NaN
120 2014-03-24    2          86.0            NaN                NaN
121 2014-03-22    0          49.0            NaN                NaN

In [61]:
#시간 인덱스 생성
head_range = pd.date_range(start='2014-12-31',end='2015-01-05')
print(head_range)

DatetimeIndex(['2014-12-31', '2015-01-01', '2015-01-02', '2015-01-03',
               '2015-01-04', '2015-01-05'],
              dtype='datetime64[ns]', freq='D')

In [62]:
#ebola 데이터프레임의 앞쪽 5개의 데이터를 추출하여 새로운 데이터프레임 생성
ebola_5 = ebola.head()
ebola_5

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,2015-01-05,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,2015-01-04,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,2015-01-03,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,2015-01-02,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-12-31,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN

In [63]:
#새로운 데이터프레임에서 Date열을 인덱스로 지정
ebola_5.index = ebola_5['Date']
#앞에서 생성한 head_range 시간 범위를 새로운 인덱스로 지정
ebola_5.reindex(head_range)

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
2014-12-31,2014-12-31,284.0,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN
2015-01-01,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-02,2015-01-02,286.0,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-03,2015-01-03,287.0,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
2015-01-04,2015-01-04,288.0,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2015-01-05,2015-01-05,289.0,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN

#알아두면 좋아요<br>
##시간 범위의 주기 설정하기

data_range()내에 있는 freq속성 이용하기

In [64]:
#data_range()메서드의 freq인잣값을 B로 설정
#freq='B' 이면 평일만 포함시킨 DatatimeIndex 를 만듦.
print(pd.date_range('2017-01-01','2017-01-07',freq="B"))

DatetimeIndex(['2017-01-02', '2017-01-03', '2017-01-04', '2017-01-05',
               '2017-01-06'],
              dtype='datetime64[ns]', freq='B')

#시간 범위 수정하고 데이터 밀어내기 - shift 메서드

에볼라의 확산 속도 비교하기

In [94]:
import matplotlib.pyplot as plt
%matplotlib notebook

In [81]:
ebola.index = ebola['Date']
ebola

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
Date,,,,,,,,,,,,,,,,,,
2015-01-05,2015-01-05,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
2015-01-04,2015-01-04,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2015-01-03,2015-01-03,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
2015-01-02,2015-01-02,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-31,2014-12-31,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-03-27,2014-03-27,5,103.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,66.0,6.0,5.0,NaN,NaN,NaN,NaN,NaN
2014-03-26,2014-03-26,4,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-03-25,2014-03-25,3,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-03-24,2014-03-24,2,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-03-22,2014-03-22,0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
fig,ax = plt.subplots()

In [96]:
ax = ebola.iloc[0:,1:].plot(ax=ax)
ax.legend(fontsize = 7, loc =2, borderaxespad = 0)

In [97]:
plt.show()

In [98]:
#각 나라의 발병일을 처음 에볼라가 발생한 Guinea와 동일한 위치로 옮긴다.
ebola_sub = ebola[['Day','Cases_Guinea','Cases_Liberia']]

In [100]:
print(ebola_sub.tail(10))

            Day  Cases_Guinea  Cases_Liberia
Date
2014-04-04   13         143.0           18.0
2014-04-01   10         127.0            8.0
2014-03-31    9         122.0            8.0
2014-03-29    7         112.0            7.0
2014-03-28    6         112.0            3.0
2014-03-27    5         103.0            8.0
2014-03-26    4          86.0            NaN
2014-03-25    3          86.0            NaN
2014-03-24    2          86.0            NaN
2014-03-22    0          49.0            NaN

In [ ]:
#그래프를 그리기 위한 데이터프레임 준비하기
ebola = pd.read.csv('')